steps:
  # First create a fake tag we'll use throughout the CI build process below.
  # Unfortunately, GCB has no concept of dynamically creating substitutions or
  # passing ENV vars between steps, so the best we can do is to create a file
  # containing our tag in the shared workspace which other steps can inspect.
  - name: bash
    script: |
      date +'0.0.%s-incompatible' > /workspace/fake_tag
      cat /workspace/fake_tag
  ### Build the bootloader binary and upload it to GCS.
  # Use the dockerfile to build an image containing the bootloader artifact.
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --build-arg=TAMAGO_VERSION=${_TAMAGO_VERSION} \
          --build-arg=GIT_SEMVER_TAG=$(cat /workspace/fake_tag) \
          --build-arg=LOG_ORIGIN=${_ORIGIN} \
          --build-arg=LOG_PUBLIC_KEY=${_LOG_PUBLIC_KEY} \
          --build-arg=OS_PUBLIC_KEY1=${_OS_PUBLIC_KEY1} \
          --build-arg=OS_PUBLIC_KEY2=${_OS_PUBLIC_KEY2} \
          --build-arg=BEE=${_BEE} \
          --build-arg=CONSOLE=${_CONSOLE} \
          -t builder-image \
          .
  # Prepare a container with a copy of the artifacts.
  - name: gcr.io/cloud-builders/docker
    args:
      - create
      - --name
      - builder_scratch
      - builder-image
  # Copy the artifacts from the container to the Cloud Build VM.
  - name: gcr.io/cloud-builders/docker
    args:
      - cp
      - builder_scratch:/build
      - output
  # List the artifacts.
  - name: bash
    args:
      - ls
      - output
  # Copy the artifacts from the Cloud Build VM to GCS.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage cp \
          output/armored-witness-boot.imx \
          gs://${_FIRMWARE_BUCKET}/$(sha256sum output/armored-witness-boot.imx | cut -f1 -d" ")
  # HAB: Create SRK table & hash
  # TODO(al): we should probably store the generated SRK/hash in a GCS bucket and then compare each time to ensure that nothing bad has happened with our PKI.
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        go run github.com/usbarmory/crucible/cmd/habtool@c77ff4b67b3cd86b4328ecbcad23394d54638ddc \
          -z gcp \
          -1 projects/armored-witness/locations/us-central1/caPools/aw-hab-ca-pool-rev0-ci/certificateAuthorities/hab-srk1-rev4-ci \
          -2 projects/armored-witness/locations/us-central1/caPools/aw-hab-ca-pool-rev0-ci/certificateAuthorities/hab-srk2-rev4-ci \
          -3 projects/armored-witness/locations/us-central1/caPools/aw-hab-ca-pool-rev0-ci/certificateAuthorities/hab-srk3-rev4-ci \
          -4 projects/armored-witness/locations/us-central1/caPools/aw-hab-ca-pool-rev0-ci/certificateAuthorities/hab-srk4-rev4-ci \
          -o output/gcp_hab_rev4_ci_srk.hash \
          -t output/gcp_hab_rev4_ci_srk.srk
  # Assert SRK hash value
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        if [ -n "${_EXPECTED_SRK_HASH}" ]; then \
          GOT=$(od -An -tx1 output/gcp_hab_rev4_ci_srk.hash | tr -d ' \n'); \
          if [ "${_EXPECTED_SRK_HASH}" != "$${GOT}" ]; then \
            echo "Got SRK hash '$${GOT}'"; \
            echo "Expected SRK hash '${_EXPECTED_SRK_HASH}'"; \
            exit 1; \
          fi; \
        fi
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        go run github.com/usbarmory/crucible/cmd/habtool@c77ff4b67b3cd86b4328ecbcad23394d54638ddc \
          -z gcp \
          -a projects/1071548024491/locations/us-central1/caPools/aw-hab-ca-pool-rev0-ci/certificates/hab-csf1-rev4-ci \
          -A projects/armored-witness/locations/global/keyRings/hab-ci/cryptoKeys/hab-csf1-rev4-ci/cryptoKeyVersions/1 \
          -b projects/1071548024491/locations/us-central1/caPools/aw-hab-ca-pool-rev0-ci/certificates/hab-img1-rev4-ci \
          -B projects/armored-witness/locations/global/keyRings/hab-ci/cryptoKeys/hab-img1-rev4-ci/cryptoKeyVersions/1 \
          -x 1 \
          -t output/gcp_hab_rev4_ci_srk.srk \
          -i output/armored-witness-boot.imx \
          -o output/armored-witness-boot.csf
  # Copy the HAB signature into the CAS
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage cp \
          output/armored-witness-boot.csf \
          gs://${_FIRMWARE_BUCKET}/$(sha256sum output/armored-witness-boot.csf | cut -f1 -d" ")
  ### Construct log entry / Claimant Model statement.
  # This step needs to be a bash script in order to substitute the fake tag in
  # the command args.
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        go run github.com/transparency-dev/armored-witness/cmd/manifest@main \
          create \
          --git_tag=$(cat /workspace/fake_tag) \
          --git_commit_fingerprint=${COMMIT_SHA} \
          --firmware_file=output/armored-witness-boot.imx \
          --firmware_type=BOOTLOADER \
          --tamago_version=${_TAMAGO_VERSION} \
          --build_env="LOG_ORIGIN=${_ORIGIN}" \
          --build_env="LOG_PUBLIC_KEY=${_LOG_PUBLIC_KEY}" \
          --build_env="OS_PUBLIC_KEY1=${_OS_PUBLIC_KEY1}" \
          --build_env="OS_PUBLIC_KEY2=${_OS_PUBLIC_KEY2}" \
          --build_env="BEE=${_BEE}" \
          --build_env="CONSOLE=${_CONSOLE}" \
          --hab_signature_file=output/armored-witness-boot.csf \
          --hab_target=ci \
          --raw \
          --output_file=output/boot_manifest_unsigned.json
  # Sign the log entry.
  - name: golang
    args:
      - go
      - run
      - github.com/transparency-dev/armored-witness/cmd/sign@main
      - --project_name=${PROJECT_ID}
      - --release=ci
      - --artefact=boot
      - --manifest_file=output/boot_manifest_unsigned.json
      - --output_file=output/boot_manifest
  # Print the content of the signed manifest.
  - name: bash
    args:
      - cat
      - output/boot_manifest
  ### Write the firmware release to the transparency log.
  # Copy the log entry to the sequence bucket, preparing to write to log.
  #
  # Use the SHA256 of the manifest as the name of the manifest. This allows
  # multiple triggers to run without colliding.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage cp output/boot_manifest \
        gs://${_LOG_NAME}/${_ENTRIES_DIR}/$(sha256sum output/boot_manifest | cut -f1 -d" ")/boot_manifest
  # Sequence log entry.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - >
        gcloud functions call sequence \

        --data="{
          \"entriesDir\": \"${_ENTRIES_DIR}/$(sha256sum output/boot_manifest | cut -f1 -d" ")\",
          \"origin\": \"${_ORIGIN}\",
          \"bucket\": \"${_LOG_NAME}\",
          \"kmsKeyName\": \"ft-log-ci\",
          \"kmsKeyRing\": \"firmware-release-ci\",
          \"kmsKeyVersion\": ${_KEY_VERSION},
          \"kmsKeyLocation\": \"global\",
          \"noteKeyName\": \"transparency.dev-aw-ftlog-ci\",
          \"checkpointCacheControl\": \"${_CHECKPOINT_CACHE}\"
        }"
  # Integrate log entry.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - call
      - integrate
      - --data
      - >-
        {
          "origin": "${_ORIGIN}",
          "bucket": "${_LOG_NAME}",
          "kmsKeyName": "ft-log-ci",
          "kmsKeyRing": "firmware-release-ci",
          "kmsKeyVersion": ${_KEY_VERSION},
          "kmsKeyLocation": "global",
          "noteKeyName": "transparency.dev-aw-ftlog-ci",
          "checkpointCacheControl": "${_CHECKPOINT_CACHE}"
        }
  # Clean up the file we added to the _ENTRIES_DIR bucket now that it's been
  # integrated to the log.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage rm \
        gs://${_LOG_NAME}/${_ENTRIES_DIR}/$(sha256sum output/boot_manifest | cut -f1 -d" ")/boot_manifest
substitutions:
  # Build-related.
  _FIRMWARE_BUCKET: armored-witness-firmware-ci-1
  _TAMAGO_VERSION: '1.21.5'
  _BEE: '1'
  _CONSOLE: 'on'
  # Log-related.
  _ENTRIES_DIR: firmware-log-sequence
  # This must correspond with the trailing number on the _FIRMWARE_BUCKET, _ORIGIN, _LOG_NAME values.
  _KEY_VERSION: '1'
  _LOG_NAME: armored-witness-firmware-log-ci-1
  _ORIGIN: transparency.dev/armored-witness/firmware_transparency/ci/1
  _LOG_PUBLIC_KEY: transparency.dev-aw-ftlog-ci+f5479c1e+AR6gW0mycDtL17iM2uvQUThJsoiuSRirstEj9a5AdCCu
  _OS_PUBLIC_KEY1: transparency.dev-aw-os1-ci+7a0eaef3+AcsqvmrcKIbs21H2Bm2fWb6oFWn/9MmLGNc6NLJty2eQ
  _OS_PUBLIC_KEY2: transparency.dev-aw-os2-ci+af8e4114+AbBJk5MgxRB+68KhGojhUdSt1ts5GAdRIT1Eq9zEkgQh
  _CHECKPOINT_CACHE: 'public, max-age=30'
  # Pinned SRK hash
  _EXPECTED_SRK_HASH: 'b8ba457320663bf006accd3c57e06720e63b21ce5351cb91b4650690bb08d85a'
