steps:
  ### Build the bootloader binary and upload it to GCS.
  # Use the dockerfile to build an image containing the bootloader artifact.
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - TAMAGO_VERSION=${_TAMAGO_VERSION}
      - --build-arg
      - LOG_ORIGIN=${_ORIGIN}
      - -t
      - builder-image
      - .
  # Prepare a container with a copy of the artifacts.
  - name: gcr.io/cloud-builders/docker
    args:
      - create
      - --name
      - builder_scratch
      - builder-image
  # Copy the artifacts from the container to the Cloud Build VM.
  - name: gcr.io/cloud-builders/docker
    args:
      - cp
      - builder_scratch:/build
      - output
  # List the artifacts.
  - name: bash
    args:
      - ls
      - output
  # HAB: Create SRK table & hash
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        go run github.com/usbarmory/crucible/cmd/habtool@c77ff4b67b3cd86b4328ecbcad23394d54638ddc \
          -z gcp \
          -1 projects/armored-witness/locations/us-central1/caPools/aw-hab-ca-pool-rev0-presubmit/certificateAuthorities/hab-srk1-rev0-presubmit \
          -2 projects/armored-witness/locations/us-central1/caPools/aw-hab-ca-pool-rev0-presubmit/certificateAuthorities/hab-srk2-rev0-presubmit \
          -3 projects/armored-witness/locations/us-central1/caPools/aw-hab-ca-pool-rev0-presubmit/certificateAuthorities/hab-srk3-rev0-presubmit \
          -4 projects/armored-witness/locations/us-central1/caPools/aw-hab-ca-pool-rev0-presubmit/certificateAuthorities/hab-srk4-rev0-presubmit \
          -o output/gcp_hab_rev0_presubmit_srk.hash \
          -t output/gcp_hab_rev0_presubmit_srk.srk
    # Assert SRK hash value
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        if [ -n "${_EXPECTED_SRK_HASH}" ]; then \
          GOT=$(od -An -tx1 output/gcp_hab_rev0_presubmit_srk.hash | tr -d ' \n'); \
          if [ "${_EXPECTED_SRK_HASH}" != "$${GOT}" ]; then \
            echo "Got SRK hash '$${GOT}'"; \
            echo "Expected SRK hash '${_EXPECTED_SRK_HASH}'"; \
            exit 1; \
          fi; \
        fi;
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        go run github.com/usbarmory/crucible/cmd/habtool@c77ff4b67b3cd86b4328ecbcad23394d54638ddc \
          -z gcp \
          -a projects/1071548024491/locations/us-central1/caPools/aw-hab-ca-pool-rev0-presubmit/certificates/hab-csf1-rev0-presubmit \
          -A projects/armored-witness/locations/global/keyRings/hab-presubmit/cryptoKeys/hab-csf1-rev0-presubmit/cryptoKeyVersions/1 \
          -b projects/1071548024491/locations/us-central1/caPools/aw-hab-ca-pool-rev0-presubmit/certificates/hab-img1-rev0-presubmit \
          -B projects/armored-witness/locations/global/keyRings/hab-presubmit/cryptoKeys/hab-img1-rev0-presubmit/cryptoKeyVersions/1 \
          -x 1 \
          -t output/gcp_hab_rev0_presubmit_srk.srk \
          -i output/armored-witness-boot.imx \
          -o output/armored-witness-boot.csf
  ### Construct log entry / Claimant Model statement.
  # This step needs to be a bash script in order to substitute the fake tag in
  # the command args.
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        go run github.com/transparency-dev/armored-witness/cmd/manifest@main \
          create \
          --git_tag=${_MANUAL_TAG} \
          --git_commit_fingerprint=${COMMIT_SHA} \
          --firmware_file=output/armored-witness-boot.imx \
          --firmware_type=BOOTLOADER \
          --tamago_version=${_TAMAGO_VERSION} \
          --hab_signature_file=output/armored-witness-boot.csf \
          --hab_target=presubmit \
          --raw \
          --output_file=output/boot_manifest_unsigned.json
  # TODO: sign the log entry with github.com/transparency-dev/armored-witness/cmd/sign
  # after we create presubmit keys.
  #
  # Print the content of the signed manifest.
  - name: bash
    args:
      - cat
      - output/boot_manifest_unsigned.json
substitutions:
  # Note that to be a valid CloudBuild config these MUST all be strings.
  # Without explicit quotes, some things may be interpreted as other types since
  # this is a YAML file, so to avoid future tears let's keep these all quoted.
  #
  # Build-related.
  _MANUAL_TAG: '0.0.0'
  _TAMAGO_VERSION: '1.22.0'
  _ORIGIN: 'transparency.dev/armored-witness/firmware_transparency/presubmit/1'
  # Pinned SRK hash
  _EXPECTED_SRK_HASH: 'c91245871a69bd54b9ebd0e540b42c485396d19c338c8a94dc1c4c3a42a8c25e'
